services:
  postgres:
    container_name: postgres_cnt
    image: postgres:14
    environment:
      POSTGRES_USER: "xenous"
      POSTGRES_PASSWORD: "xenous"
    ports:
      - "6444:5432"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xenous -d xenous"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
        
networks:
  postgres:
    driver: bridge